const strings = {
  "home-page-header-L1": "The World's First 3D & AR NFT Multichain Platform and",
  "home-page-header-L2": " Video Game",
  "home-page-sub-header-L1": "EARN PROFIT",
  "home-page-sub-header-L2": "BY OWNING VIRTUAL TAXIS, GAS STATIONS & SERVICES",
  "exchanges": "Exchanges",
  "market-place": "Marketplace",
  "bridge": "Bridge",
  "buy-assets": "Buy assets",
  "game-beta": "Sign Up",
  "platform": "Platform",
  "roadmap": "Roadmap",
  "tokens": "Tokenomics",
  "audits": "Audits",
  "team": "Team",
  "home": "Home",
  "store": "Store",
  "my-assets": "My Assets",
  "stacking": "Stacking",
  "submit-nft": "Submit NFT",
  "q-a": "Q&A",
  "marketplace-subheader-1": "Marketplace is now Multichain. Change Metamask to the chain you want to browse NFTs on.",
  "bad-username": "Username must be at least 6 lower-case alphanumeric characters.",
  "bad-email": "Please enter your email.",
  "bad-wallet": "Please enter your wallet address.",
  "bad-password": "Password must be at least 6 characters",
  "password-mismatch": "Password and confirmation must match.",
  "enter-new-password": "Please input the new password for the account with wallet"
}
export default strings;